version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:5.0
    container_name: redis
