# Generated by Django 4.1.5 on 2023-01-05 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'Usd'), (1, 'Eur'), (2, 'Eth')])),
                ('amount', models.DecimalField(decimal_places=8, max_digits=22)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gift_card_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giftcards.giftcardrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('address', models.CharField(max_length=42)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='giftcards.giftcard')),
            ],
        ),
    ]
